name: go

on:
  push:
    tags:
    - v*
    branches:
    - main
  pull_request:

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        version: v1.32

  mod-tidy:
    name: go-mod-tidy
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup-go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16.x
    - name: cache
      uses: actions/cache@v2.1.5
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: tidy
      run: |
        cp go.sum{,.old}
        go mod tidy
        diff go.sum{.old,}

  test:
    name: go-${{ matrix.go-version }}-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
        - 1.16.x
        - 1.17.x
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup-go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: ${{ matrix.go-version }}
    - name: cache
      uses: actions/cache@v2.1.5
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: go-test
      run: go test -v ./...
